# Generated by Django 4.2.3 on 2023-07-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
